mediacms-io/mediacms

- files/context_processors.py
- files/feeds.py
- files/management_views.py
- files/urls.py
- files/views.py
- templates/common/head-links.html
Brings an /rss for all pages EXCEPT for search pages where the current search (term/category/tag) results are returned
Checked with https://www.coderedcorp.com/tools/rss-preview/
> introduce rss and custom rss

- cms/permissions.py
- cms/settings.py
- files/methods.py
- files/models.py
- files/views.py
1. when media gets reported, notify media user too
2. change the reported message to include number of times before the media goes private
3. users get notified when comments are added to their media
> provide notifications on commenting

- README.md
> on Readme page resize screenshots

- .gitignore
- Dockerfile
- deploy/docker/entrypoint.sh
- install.sh
* Fix docker chown recursion performance
* upgrades bento4
> Fix docker chown recursion performance and bento4 upgrade

- files/helpers.py
- files/models.py
- files/tasks.py
- files/views.py
- setup.cfg
makes flake8 a little more strict
> improvements on flake8

- cms/settings.py
- files/feeds.py
- files/helpers.py
- files/models.py
- files/views.py
- setup.cfg
- users/views.py
changes based on flake8 and also https://lgtm.com/projects/g/mediacms-io/mediacms/?mode=list
> Feat flake8 strength

- README.md
- docs/Configuration.md
- docs/Docker_Compose.md
- docs/Docker_deployment.md
- docs/Single_Server.md
> cleanup docs and add some more regarding Docker installation

- docs/Docker_deployment.md
> Docker compose docs

- docs/robots_and_analytics.md
Added instructions to add Google Analytics and robots.txt
*Pre-deploy*
*Post-deploy*
> Added instructions inside robots_and_analytics.md

- README.md
> add Releases section on Readme

- README.md
- docs/Configuration.md
- docs/admins_docs.md
- docs/developers_docs.md
> documentation improvements

- Dockerfile
* restores /tmp that was deleted while adding static ffmpeg
> restore /tmp that was deleted while adding static ffmpeg

- tests/test_selenium_smoke.py
> remove smoke test that breaks

- files/tests/user_utils.py
> small typo

- files/models.py
pass all arguments that are going to be indexed from clean function - while saving a Media information
> improve validation on text indexing, for search

- .coveragerc
- .github/workflows/python.yml
adds instructions to get coverage
> adds instructions to get coverage

- files/models.py
> correctly identify audio

- cli-tool/cli.py
- files/models.py
> remove zombie thumbnails

- deploy/docker/nginx_http_only.conf
> enable cors for media dir

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- actions/migrations/0001_initial.py
- actions/migrations/0002_mediaaction_media.py
- actions/migrations/0003_auto_20201201_0712.py
- cms/custom_pagination.py
- files/feeds.py
- files/methods.py
- files/migrations/0001_initial.py
- files/migrations/0002_auto_20201201_0712.py
- files/migrations/0003_auto_20210927_1245.py
- files/models.py
- files/tasks.py
- users/migrations/0001_initial.py
- users/views.py
> update versions for pre-commit

- cli-tool/cli.py
Added One Word, a missing f for f string for abspath arg in upload_media func
*Pre-deploy*
*Post-deploy*
> cli.py missing f string

- deploy/docker/prestart.sh
- files/tasks.py
> Feat celery run

- frontend/src/static/js/components/media-actions/MediaMoreOptionsIcon.jsx
Fixes secondary issue in #882 
*Pre-deploy*
*Post-deploy*
> Fix null bug in More Options button

- files/tasks.py
give more limit to chunkize media task
> feat: increase task limit

- cms/settings.py
> feat: comment URL

- files/models.py
> fix: black

- cms/dev_settings.py
- cms/settings.py
- requirements.txt
Fixes https://github.com/mediacms-io/mediacms/issues/1191
> fix: crispy forms

- docker-compose-dev.yaml
- docker-compose/docker-compose-dev-updated.yaml
- docker-compose/docker-compose-http-proxy.yaml
- docker-compose/docker-compose-https-proxy.yaml
- docker-compose/docker-compose-letsencrypt.yaml
- docker-compose/docker-compose-named-volumes.yaml
move docker compose files to docker-compose dir
> move docker compose files in dir

- cms/settings.py
- cms/version.py
fix issue with imports ordering
> fix: issue with import

- files/feeds.py
- files/helpers.py
- files/methods.py
- files/models.py
- files/tasks.py
- files/views.py
- uploader/utils.py
- users/models.py
> replace format with fstrings

- cms/version.py
- files/context_processors.py
- templates/common/body-scripts.html
- templates/common/head-links.html
> feat: pass version on static files

- docs/admins_docs.md
- files/forms.py
- files/models/media.py
> fix: delete media

- docs/admins_docs.md
- docs/saml_entraid_setup.md
This PR adds a guide detailing how to configure Microsoft Entra ID as a SAML Identity Provider for MediaCMS, including setup, testing, and troubleshooting.
Although this guide is specifically about EntraID, the set of steps taken herein can help others easily apply the correct setup process to other SAML providers.
> Docs Update with SAML Deployement Guide and Troubleshooting

- cms/settings.py
- docs/admins_docs.md
- files/context_processors.py
- templates/config/installation/site.html
> feat: allow portal logo override
