mediacms-io/mediacms

.gitignore
Dockerfile
deploy/docker/entrypoint.sh
deploy/docker/local_settings.py

* Had trimmed out too much from the bento-sdk
* placed the bento a level below the source, so it is not mounted over by the source folder

fixes hls generation for docker builds

---

deploy/docker/entrypoint.sh

* removes dangling pids which could prevent celery workers from starting reliably

docker remove dangling pids

---

files/models.py
files/views.py

1. allow an unlisted media to be added to a playlist (not only public media)
2. allow playlists with audio only to function - fixes https://github.com/mediacms-io/mediacms/issues/153

allow media of all states to be added to playlist

---

.github/workflows/lint_test.yml
.pre-commit-config.yaml
README.md
pyproject.toml
requirements.txt
setup.cfg

This fixes #131 
@mgogoulos please let me know if there are any further changes required.
Thank you!

Add pre-commit 

---

cms/settings.py
requirements.txt

Adds an option  GLOBAL_LOGIN_REQUIRED (False by default) that when set to True only logged in users may visit the portal

Feat login required

---

docker-compose-letsencrypt.yaml

An example that shows how you can do letsencrypt for a docker-based mediacms deployment.
In this example, I have used named volumes, but feel free to use your host volumes as in `docker-compose.yaml`

adding docker letsencrypt example

---

Dockerfile
deploy/docker/entrypoint.sh
deploy/docker/reverse_proxy/client_max_body_size.conf
deploy/docker/supervisord/supervisord-celery_beat.conf
deploy/docker/supervisord/supervisord-celery_long.conf
deploy/docker/supervisord/supervisord-celery_short.conf

Stores celery pids within a running container state. See: https://github.com/mediacms-io/mediacms/issues/224#issue-923117670
*Pre-deploy*
N/A
*Post-deploy*
N/A

keep pids in container scope

---

Dockerfile
install.sh

Instead of using the system packages, install a recent ffmpeg static build.
This gets you more bugfixes and newer features.
Simplifies the OS check and package installation, because it was duplicated.
*Pre-deploy*
*nothing*
*Post-deploy*
*nothing*

install more recent ffmpeg

---

docker-compose-http-proxy.yaml
docker-compose-https-proxy.yaml
docker-compose-letsencrypt.yaml
docker-compose-named-volumes.yaml
docker-compose.yaml

* Migrations are run as a pre-start process, there is no need to waste resources by unnecessarily keeping the container running when the migrations have been completed.
* This MR solves this issue
*Pre-deploy*
N/A
*Post-deploy*
N/A

shutdown migrations container when migrations have completed

---

Dockerfile
deploy/docker/prestart.sh

addresses https://github.com/mediacms-io/mediacms/issues/118 , doesn't run all steps from prestart.sh every time migrations service starts but rather when DB is empty, and system is uninitialized
also sets a random password for admin (used to be a fixed pw) so update on documentation is needed

optimize migrations service to not run all actions every time

---

Dockerfile
deploy/docker/prestart.sh
docker-compose-http-proxy.yaml
docker-compose-https-proxy.yaml
docker-compose-letsencrypt.yaml
docker-compose-named-volumes.yaml
docker-compose.yaml
docs/Docker_Compose.md

Handle sensitive variables on docker-compose files rather than Dockerfile, thus changes are applied without having to build an image. 
We may optionally add env files to take care of them, but for now this fixes existing status where setting the password has no effect (same for the username)

move envs from Dockerfile to docker-compose files

---

docs/admins_docs.md

I added an entry under 'Configuration 'per discussion in the Q&A section:
https://github.com/mediacms-io/mediacms/discussions/422

Add configuration for only member access to media

---

docker-compose-dev.yaml
docs/developers_docs.md

Fix #471 by adding default values for admin user attributes in `docker-compose-dev.yaml`
A few info added to `developers_docs.md`, as well.

Fix admin user creation

---

cms/settings.py
files/context_processors.py
templates/cms/index.html

This pull request adds the ability to specify a meta description tag for the homepage for search engines.
*Pre-deploy*
*Post-deploy*

Add meta description tag for search engines

---

files/context_processors.py
templates/config/installation/site.html

This fixes an issue where URIs all over the system were output in the form:
```
https://example.com//view?m=(video ID)
```
...even when the `FRONTEND_HOST` and `SSL_FRONTEND_HOST` did not have a trailing slash.  This was especially problematic with the meta `canonical` tag, which was pretty much always a different URI than the page that was outputting it, but many of the other URIs on the page (especially in the metadata) were including the double slashes as well.
*Pre-deploy*
*Post-deploy*

Fix double slashes in URIs

---

docs/admins_docs.md

It's clarified how to exactly modify `encode profiles`. Looks like the previous statements were wrong.

Encode profiles doc

---

cms/settings.py

This PR adds the password/confirm-email to the whitelisted pages for when global login is required. The matching allows subpages of those pages to be whitelisted as well, such as /accounts/password/reset/ or /accounts/password/change/, as well as the tokens used in the email confirmation system.
This fixes email verification as well as password resets when global login is required
Properly fixes #770

Allow password reset & email verify pages on global login required

---

files/helpers.py
files/models.py
files/views.py

Use a function that enables tags to contain other characters as well, not only in the English alphabet. Special characters, spaces etc are still stripped

allow tags to contain chars, not only English alphabet

---

files/models.py

Adds an extra step to identify AVI (and probably other types) as videos, instead of them being identified as audio
This is an improvement on https://github.com/mediacms-io/mediacms/pull/505/files

fix issue with AVI not being recognised as videos

---

files/models.py

Workaround for vertical videos, attempt to provide the width as the key for resolution, rather than the height, in order to avoid showing too many options on the Quality listing - https://github.com/mediacms-io/mediacms/issues/824

check resolution for HLS

---

docker-compose-dev.yaml
docker-compose-http-proxy.yaml
docker-compose-https-proxy.yaml
docker-compose-letsencrypt.yaml
docker-compose-named-volumes.yaml
docker-compose.yaml

This PR includes the following changes:
- Upgraded the DB to the latest stable alpine version. The version is pinned with MAJOR.MINOR (15.2), but can be changed to MAJOR (15) only if desired.
- Updated the health check command to use environment variables instead of a hard-coded value.
- Added the timezone environment variable TZ to the DB.
The changes were tested on a VM server using the docker compose stacks.

Upgrade postgres docker compose

---

files/admin.py

When looking at the admin screen for Encodings, there is almost no information presented until you click on a particular encoding.  This adds a few useful fields to that screen as additional columns and filters.
*Pre-deploy*
*Post-deploy*

Add useful fields to the Encodings admin screen

---

files/admin.py

This adds an action to the MediaCMS Administration section to allow you to select Media items and generate missing encodings.  That way, if for some reason an encoding fails or if you enable other encoding profiles (such as enabling VP9 profiles after a video is posted), you can reprocess the media to fill in the gaps.
Fixes #874
*Pre-deploy*
*Post-deploy*
(EDIT) Typo

Add admin action to generate missing encodings for a particular Media

---

docker-compose-dev.yaml
docker-compose-http-proxy.yaml
docker-compose-https-proxy.yaml
docker-compose-letsencrypt.yaml
docker-compose-named-volumes.yaml
docker-compose.yaml

Fixes "garbage" output: 
`db_1 FATAL: role "root" does not exist` 
as discussed in #1002 and #894 
first proposed by @Nouri-redouane 
*Pre-deploy*
*Post-deploy*

Fix postgres role output

---

uploader/fineuploader.py

This PR is adding extra validation to fix a potential issue with file uploads + specifying arbitrary uuid or filename that could end up in replacing files in the filesystem.

security fix: add validation to files uploading to avoid client side pushing arbitr…s

---

cms/permissions.py
cms/settings.py
files/views.py

Fixes #216 
This allows the site operator control over who is able to comment.  It is configured by default to allow all logged-in users to be able to comment, but can be changed to only allow email_verified users or advanced users to comment.  This also fixes #216 since it separates out the comment permissions from the media posting permissions.
It does not, however, add anonymous commenting as was mentioned in passing at the end of #216.  That change is a little more difficult and outside of the scope of what I could quickly accomplish.
*Pre-deploy*
*Post-deploy*

Fix commenting by regular users when posting media requires advanced permissions

---

deploy/docker/local_settings.py

Support for reading environment variables
FRONTEND_HOST, PORTAL_NAME, PORTAL_NAME, REDIS_LOCATION
POSTGRES_HOST, POSTGRES_PORT, POSTGRES_NAME, POSTGRES_USER, POSTGRES_PASSWORD
*Pre-deploy*
*Post-deploy*

Support for reading environment variables

---

files/models.py

Simply Sorted the order of subtitles by the first letter of any language.
- Simply Created an other variable named sorted_subtitles
- assigned return of sorted function which will take all the subtitles and condition on basis sorting will be performed
- then replace original subtitles with sorted_subtitles

#845 Issue : Re-Arranged Subtitles by first letter of language

---

cms/dev_settings.py
cms/settings.py
cms/urls.py
deploy/docker/nginx_http_only.conf
deploy/local_install/mediacms.io
files/context_processors.py
files/methods.py
files/views.py
requirements.txt
templates/cms/edit_media.html
templates/cms/media.html
templates/cms/user_edit.html
templates/config/core/url.html

* remove ckeditor - not in use
* add more strict default password validators
* set Django admin as configurable URL
* add nginx HSTS and CSP headers
* enable moving from private to unlisted in the PORTAL_WORKFLOW private
* on default comments listing, show only comments for public media
* in case of a private media, dont expose any unneeded metadata

Bulk fixes

---

Dockerfile

Fixes: L27 'as' and 'FROM' keywords' casing do not match
*Pre-deploy*
*Post-deploy*

Nit: Fix Docker WARN: FromAsCasing

---

files/forms.py

By default, Django uses type=text for the date input, which respects the locale settings. However, when changing the input type to date, it should only accept YYYY-MM-DD format so the input field can be properly handled.
Before:
After:

Fixing date picker in edit media

---

files/models/category.py
files/models/media.py
files/models/playlist.py

The title was being spliced as title[:99] which fixed it's length to 99 characters, so I updated it to [:100] in the playlists, categories and media models.
#1339

Updated the title splicing length to 100 in playlist, category and media models
